#配置数据源
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car
    username: root
    password: ok
  mvc:
    view:
      prefix: /
      suffix: .jsp
#日志
logging:
  level:
    root: info
    com.zb.mapper: debug
  config: classpath:lombok-spring.xml
#mybatis映射文件地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9090